apiVersion: v1
kind: Service
metadata:
  name: mongo-replica
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    appdb: db
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-hostpath
  labels:
    type: local
    app: db
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/pv"
---
apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: mongo-config
data:
  MONGODB_DATABASE: "K8Sproject"
  MONGODB_BIND_IP: "0.0.0.0"
  MONGODB_REPL_SET: "rs0"
---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-credentials
type: Opaque
data:
  username: YWRtaW4=
  password: YWRtaW4=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
spec:
  selector:
    matchLabels:
      appdb: db
  replicas: 1
  template:
    metadata:
      labels:
        appdb: db
    spec:
      containers:
        - name: db
          image: mongo:3.6
          ports:
            - containerPort: 27017
          env:
            - name: MONGODB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: mongo-config
                  key: MONGODB_DATABASE
            - name: MONGODB_BIND_IP
              valueFrom:
                configMapKeyRef:
                  name: mongo-config
                  key: MONGODB_BIND_IP
            - name: MONGODB_REPL_SET
              valueFrom:
                configMapKeyRef:
                  name: mongo-config
                  key: MONGODB_REPL_SET
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-credentials
                  key: password
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-credentials
                  key: password
          volumeMounts:
            - mountPath: /var/lib/mongodb
              name: mongo-volume
      volumes:
        - name: mongo-volume
          persistentVolumeClaim:
            claimName: mongo-pv-claim
