apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: docker.io/imanehai/frontend:latest
          ports:
            - containerPort: 80
          env:
            - name: REACT_APP_Backend_URL
              valueFrom:
                configMapKeyRef:
                  name: front-config
                  key: BACKEND_URL
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: front-config
data:
  BACKEND_URL: "http://192.168.92.112:3000"

